[package]
name = "patch-compressor"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/kumpelblase2/silkroad-patch-compressor"

[dependencies]
xz2 = "0.1.7"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
